<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:property name="eef_bottom_distance_from_center" value="0.1988"/>
  <xacro:property name="eef_tip_z_distance_from_center" value="0.4365"/>
  <xacro:property name="eef_tip_y_distance_from_center" value="0.00185"/>  

    <xacro:macro name="atl_tool" params="prefix">

        <link name="${prefix}base_link">
            <visual>
                <origin xyz="0 0 ${eef_bottom_distance_from_center}" rpy="${-pi} 0 0"/>
                <geometry>
                    <mesh filename="package://kr210_eef_support/meshes/visual/atl_tool.dae" scale="0.001 0.001 0.001"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="-0.260 0.172 ${eef_bottom_distance_from_center}" rpy="${pi/2} ${pi} 0"/>
                <geometry>
                    <mesh filename="package://kr210_eef_support/meshes/collision/atl_tool.stl" scale="0.001 0.001 0.001"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 ${eef_bottom_distance_from_center-0.008}" rpy="${-pi/2} 0 0"/>
                <geometry>
                    <mesh filename="package://kr210_eef_support/meshes/visual/kuka_quickrelease.dae" scale="0.001 0.001 0.001"/> 
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://kr210_eef_support/meshes/collision/kuka_quickrelease.stl" scale="0.001 0.001 0.001"/>
                </geometry>
            </collision>
        </link>

        <link name="${prefix}tool_tip"/>

        <joint name="${prefix}tool_tip_to_${prefix}base_link" type="fixed">
            <parent link= "${prefix}base_link"/>
            <child link= "${prefix}tool_tip"/>
            <origin xyz="0 ${eef_tip_y_distance_from_center} ${eef_bottom_distance_from_center+eef_tip_z_distance_from_center}" rpy="0 0 0" />
        </joint>

    </xacro:macro>
</robot>
