# controller_joint_names: ["kr210_joint_a1", "kr210_joint_a2", "kr210_joint_a3", "kr210_joint_a4", "kr210_joint_a5", "kr210_joint_a6","kl2000_joint_e1","kr1_joint_e2"]
controller_joint_names: ["kr210_joint_a1", "kr210_joint_a2", "kr210_joint_a3", "kr210_joint_a4", "kr210_joint_a5", "kr210_joint_a6"]
