<?xml version="1.0"?>

<robot xmlns:xacro="http://wiki.ros.org/xacro"> 
  <!-- PROPERTIES -->
  <!-- Dimensions of the work table -->
  <xacro:property name="table_height" value="0.5"/>
  <xacro:property name="table_top_thickness" value="0.085"/>  

  <!-- INCLUDES -->
  <!-- Linear Track (with mobile base) -->
  <xacro:include filename="$(find kr210_pen_support)/urdf/parts/kl2000_linear_track_macro.xacro"/>
  <!-- Robot console (booster frame) -->
  <xacro:include filename="$(find kr210_pen_support)/urdf/parts/kl2000_console_h400_macro.xacro"/>
  <!-- Kuka KR210R2700extra robot -->
  <xacro:include filename="$(find kuka_kr210_support)/urdf/kr210r2700extra_macro.xacro"/>
  <!-- Welding Table -->
  <xacro:include filename="$(find kr210_pen_support)/urdf/parts/forster_welding_table_macro.xacro"/>
  <!-- Penholder End Effector -->
  <xacro:include filename="$(find kr210_eef_support)/urdf/penholder_macro.xacro"/>

  <!-- MACRO START  -->
  <xacro:macro name="kr210_pen" params="prefix">
    <!-- DEFINITIONS -->
    <xacro:kl2000 prefix="${prefix}kl2000_"/>  
    <xacro:kl2000_console_h400 prefix="${prefix}console_"/>
    <xacro:kuka_kr210r2700extra prefix="${prefix}kr210_"/>
    <xacro:forster_welding_table prefix="${prefix}table_"/>
    <xacro:penholder prefix="${prefix}penholder_"/>

    <!-- JOINTS -->
    <!-- Console to Linear track -->
    <joint name="${prefix}console_base_link_to_${prefix}kl2000_mobile_base" type="fixed">     
      <parent link="${prefix}kl2000_mobile_base"/>
      <child link="${prefix}console_base_link"/>     
      <origin xyz="0 0 0" rpy="0 0 0"/> 
    </joint>

    <!-- Robot to console  -->
    <joint name="${prefix}kr210_base_link_to_${prefix}console_base_link" type="fixed">     
      <parent link="${prefix}console_base_link"/>
      <child link="${prefix}kr210_base_link"/>     
      <origin xyz="0 0 0.4" rpy="0 0 ${-pi/2}"/> 
    </joint>

    <!-- Welding table to linear track -->   
    <joint name="${prefix}table_base_link_to_${prefix}kl2000_mobile_base" type="fixed">     
      <parent link="${prefix}kl2000_base_link"/>
      <child link="${prefix}table_base_link"/>     
     <origin xyz="-1.264 1.719 ${(table_height - table_top_thickness)/2}" rpy="0 0 ${-pi/2}"/>       
      <!-- <origin xyz="1.264 0.919 ${(table_height - table_top_thickness)/2}" rpy="0 0 0"/>   -->
    </joint>

    <!-- End effector to robot --> 
    <joint name="${prefix}penholder_base_link_to_${prefix}kr210_tool0" type="fixed">     
      <parent link="${prefix}kr210_tool0"/>
      <child link="${prefix}penholder_base_link"/>     
      <origin xyz="0 0 0" rpy="0 0 0"/>       
    </joint> 


  </xacro:macro>
</robot>
